%YAML:1.0

#--------------------------------------------------------------------------------------------
# Camera Parameters. Adjust them!
#--------------------------------------------------------------------------------------------

# Camera calibration and distortion parameters (OpenCV)
Camera.fx: 517.306408
Camera.fy: 516.469215
Camera.cx: 318.643040
Camera.cy: 255.313989

Camera.k1: 0.262383
Camera.k2: -0.953104
Camera.p1: -0.005358
Camera.p2: 0.002628
Camera.k3: 1.163314

Camera.width: 640
Camera.height: 480

# Camera frames per second
Camera.fps: 30.0

# IR projector baseline times fx (aprox.)
Camera.bf: 40.0

# Color order of the images (0: BGR, 1: RGB. It is ignored if images are grayscale)
Camera.RGB: 1

# Close/Far threshold. Baseline times.
ThDepth: 40.0

# Deptmap values factor
DepthMapFactor: 5000

# 0: no constraint; 1: use ground truth; 2: use imu
ConstraintType: 1
#--------------------------------------------------------------------------------------------
# ORB Parameters
#--------------------------------------------------------------------------------------------

# ORB Extractor: Number of features per image
ORBextractor.nFeatures: 1000

# ORB Extractor: Scale factor between levels in the scale pyramid
ORBextractor.scaleFactor: 1.2

# ORB Extractor: Number of levels in the scale pyramid
ORBextractor.nLevels: 8

# ORB Extractor: Fast threshold
# Image is divided in a grid. At each cell FAST are extracted imposing a minimum response.
# Firstly we impose iniThFAST. If no corners are detected we impose a lower value minThFAST
# You can lower these values if your images have low contrast
ORBextractor.iniThFAST: 20
ORBextractor.minThFAST: 7

#--------------------------------------------------------------------------------------------
# Viewer Parameters
#--------------------------------------------------------------------------------------------
Viewer.KeyFrameSize: 0.05
Viewer.KeyFrameLineWidth: 1
Viewer.GraphLineWidth: 0.9
Viewer.PointSize: 2
Viewer.CameraSize: 0.08
Viewer.CameraLineWidth: 3
Viewer.ViewpointX: 0
Viewer.ViewpointY: -0.7
Viewer.ViewpointZ: -1.8
Viewer.ViewpointF: 500
#--------------------------------------------------------------------------------------------
# Plane Extraction Parameters
#--------------------------------------------------------------------------------------------
Cloud.Dis: 3
Plane.MinSize: 500
Plane.AngleThreshold: 3.0
Plane.DistanceThreshold: 0.05
Plane.LeafSize: 0.01
Plane.MaxDistance: 10.0

#--------------------------------------------------------------------------------------------
# Plane Optimization Parameters
#--------------------------------------------------------------------------------------------
Plane.AssociationDisRef: 0.2
Plane.AssociationDisMon: 0.2
Plane.AssociationAngRef: 0.8 # 30 degree
Plane.AssociationAngMon: 0.8 # 30 degree
Plane.VerticalThreshold: 0.08716 # 85 degree
Plane.ParallelThreshold: 0.9962 # 5 degree
Plane.AngleInfo: 1
Plane.DistanceInfo: 100
Plane.Chi: 300
Plane.VPChi: 300
Plane.ParallelInfo: 0.5
Plane.VerticalInfo: 0.5

#--------------------------------------------------------------------------------------------
# Supposed Plane Extraction Parameters
#--------------------------------------------------------------------------------------------
Line.Ratio: 0.2
Line.DistanceThreshold: 0.01
Plane.ShowSPlane: 1

#--------------------------------------------------------------------------------------------
# Result File Paths
#--------------------------------------------------------------------------------------------
SavePath.Frame: "FrameTrajectory.txt"
SavePath.Keyframe: "KeyFrameTrajectory.txt"
SavePath.PlaneFeature: "PlaneFeature.txt"


